services:
  db:
    image: postgres:15.1-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}

  api:
    build: ./backend/src
    command: |
      bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn api.main:app --ssl-keyfile /secrets/key.pem --ssl-certfile /secrets/cert.pem --reload --workers 1 --host 0.0.0.0 --port 8000'
    volumes:
      - ./backend/src:/usr/src/
      - ./secrets:/secrets
    ports:
      - 8002:8000
    environment:
      - DATABASE_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db/${POSTGRES_DB}
      - MS_APP_ID=${MS_APP_ID}
      - MS_AUTHORITY_ID=${MS_AUTHORITY_ID}
      - MS_CLIENT_SECRET=${MS_CLIENT_SECRET}

    depends_on:
      - db

volumes:
  postgres_data: